In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("ILINet.csv", skiprows=1)

In [3]:
data = data[["REGION", "YEAR", "WEEK", "ILITOTAL"]]

In [4]:
data[:5]

       REGION  YEAR  WEEK ILITOTAL
0     Alabama  2010    40      249
1      Alaska  2010    40       15
2     Arizona  2010    40      172
3    Arkansas  2010    40       18
4  California  2010    40      632

In [5]:
used_regions = (data[:100]["REGION"].unique()).tolist()

In [6]:
print(len(used_regions))

52

In [7]:
df = [data[data["REGION"] == region] for region in used_regions]

In [8]:
for i in range(len(df)):
    region_df = df[i].copy()
    region_df["ILITOTAL"] = pd.to_numeric(region_df["ILITOTAL"], errors="coerce")
    region_df["YEAR"] = pd.to_numeric(region_df["YEAR"], errors="coerce")
    df[i] = region_df

In [9]:
full_df = pd.concat(df, ignore_index=True)
full_df = full_df[full_df["YEAR"] < 2018]

In [11]:
full_df.head()

    REGION  YEAR  WEEK  ILITOTAL
0  Alabama  2010    40       249
1  Alabama  2010    41       239
2  Alabama  2010    42       232
3  Alabama  2010    43       274
4  Alabama  2010    44       342

In [12]:
print(max(full_df["ILITOTAL"]))

9716

In [13]:
pivot_table = full_df.pivot_table(index=["YEAR", "WEEK"], columns="REGION", values="ILITOTAL")

In [14]:
tensor = pivot_table.values[:,:,None]
np.save("us_infections", tensor)